### ISSUE TITLE
DOUBT: Consiglio di semplificare la schema di CodiceFiscale

### ISSUE THREAD

**Issue by jackom83** [vintra73/INAD_API_estrazione#14]
https://github.com/vintra73/INAD_API_estrazione/blob/d41f2ec591903435e3e087448311f1fdf39c4747/api.inad.gov.it-openapi.yaml#L397

Lo schema in oggetto dovrebbe essere una stringa con pattern, non un oggetto con dentro una stringa con pattern.

In tal modo si rende possibile referenziare lo schema anche per i parametri delle richieste

**Comment by gcalsolaro** [comment]
Done!
