### ISSUE TITLE
DOUBT: Consiglio di semplificare la schema di DomicilioDigitale

### ISSUE THREAD

**Issue by jackom83** [vintra73/INAD_API_estrazione#15]
https://github.com/vintra73/INAD_API_estrazione/blob/d41f2ec591903435e3e087448311f1fdf39c4747/api.inad.gov.it-openapi.yaml#L422

Lo schema in oggetto dovrebbe essere una stringa con pattern, non un oggetto con dentro una stringa con pattern

**Comment by gcalsolaro** [comment]
Done!
