### ISSUE TITLE
DOUBT: l'elemento href non deve essere presente nello schema RispostaStatoRichiestaElencoDomiciliDigitali

### ISSUE THREAD

**Issue by jackom83** [vintra73/INAD_API_estrazione#16]
https://github.com/vintra73/INAD_API_estrazione/blob/d41f2ec591903435e3e087448311f1fdf39c4747/api.inad.gov.it-openapi.yaml#L516

Non è necessario inserire nella risposta che fornisce lo stato di elaborazione della "richiesta elenco" il link per il recupero delll'esito, Rispettando il pattern  [NONBLOCK_PULL_REST] questo va veicolato nell'Header Location solo in caso di response 303.

Tra l'altro veicolando lo stesso in caso di response 200 si fornirebbe un link la cui GET ha response 404 Not Found non essendo ancora pronta l'elaborazione richiesta

**Comment by gcalsolaro** [comment]
Done!
