### ISSUE TITLE
DOUBT: perché non utilizziamo schema cf?

### ISSUE THREAD

**Issue by vintra73** [vintra73/INAD_API_estrazione#3]
https://github.com/vintra73/INAD_API_estrazione/blob/d41f2ec591903435e3e087448311f1fdf39c4747/INAD_API_extraction.yaml#L115

**Comment by jackom83** [comment]
Lo schema **CodiceFiscale**  è un object non una stringa

https://github.com/vintra73/INAD_API_estrazione/blob/d41f2ec591903435e3e087448311f1fdf39c4747/api.inad.gov.it-openapi.yaml#L397

**Comment by gcalsolaro** [comment]
Done!
