### ISSUE TITLE
DOUBT: non server il pattern avendo utilizzato format

### ISSUE THREAD

**Issue by vintra73** [vintra73/INAD_API_estrazione#5]
https://github.com/vintra73/INAD_API_estrazione/blob/d41f2ec591903435e3e087448311f1fdf39c4747/api.inad.gov.it-openapi.yaml#L166

**Comment by jackom83** [comment]
Il formato **_date_** è **ISO 8601** (_YYYY-MM-DD o YYYYMMDD)_ per cui l'esempio è errato: 

` example: '03112021' `

**Comment by gcalsolaro** [comment]
Done!
