### ISSUE TITLE
DOUBT: se utilizzato format, pattern non serve

### ISSUE THREAD

**Issue by vintra73** [vintra73/INAD_API_estrazione#9]
https://github.com/vintra73/INAD_API_estrazione/blob/d41f2ec591903435e3e087448311f1fdf39c4747/api.inad.gov.it-openapi.yaml#L460

**Comment by jackom83** [comment]
Il formato **_date-time_** è **ISO 8601**  per cui è errata la descrizione:
`description: Data/Ora estrazione in formato <dd/MM/yyyy hh:mm:ss>`

**Comment by gcalsolaro** [comment]
Done!
